# 使用 Node.js LTS 版本
FROM node:22.13-alpine

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json
COPY package.json package-lock.json ./

# 安裝開發環境所需的 npm 依賴
RUN npm install

# 開放 Nuxt 3 開發模式所需的 Port
EXPOSE 3000

# 預設使用開發模式
CMD ["npm", "run", "dev"]